name: Image Resize
run-name: Image Resize
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Resize Images in resize/ directory
        run: |
          bash run_digest.sh
      - run: echo " This job's status is ${{ job.status }}."